---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pladde
--- DateTime: 15.07.2025 07:27
--- Updated: 15.07.2025
--- Reason:
---

local frameAddonLoaded = CreateFrame("Frame", "bfmFrameLoaded");

frameAddonLoaded:RegisterEvent("ADDON_LOADED");
frameAddonLoaded:RegisterEvent("PLAYER_ENTERING_WORLD");

frameAddonLoaded:SetScript("OnEvent",function(self, event, ...)
    if event == "ADDON_LOADED" and event == "PLAYER_ENTERING_WORLD" then
        DEFAULT_CHAT_FRAME:AddMessage("bfm sucessfully loaded");
    end
end)