---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pladde
--- DateTime: 15.07.2025 07:27
--- Updated: 15.07.2025 08:44
--- Reason: created mainFrame
---

local frame = CreateFrame("Frame", "bfmFrame");

frame:RegisterEvent("ADDON_LOADED");
frame:RegisterEvent("PLAYER_LOGIN");

frame:RegisterEvent("UNIT_COMBAT");
frame:RegisterEvent("UNIT_FLAGS");
frame:RegisterEvent("UNIT_ATTACK");

-- displays if the addon was sucessfully loaded on player login
frame:SetScript("OnEvent",function(self, event, ...)
    if event == "ADDON_LOADED" and event == "PLAYER_ENTERING_WORLD" then
        DEFAULT_CHAT_FRAME:AddMessage("bfm sucessfully loaded");
    end
end)

-- plays music if the player turn into a bossfight
frame:SetScript("OnEvent", function(self, event, ...)
    if event == "UNIT_COMBAT" then
        local unitID = select(1, ...)

        if not unitID or not UnitExists(unitID) then
            return;
        end

        if unitID == "player" and UnitInCombat("player") then

            local targetUnit = "target";
            if UnitExists(targetUnit) and UnitInCombat(targetUnit) then
                local targetClassification = UnitClassification(targetUnit);
                local targetLevel = UnitLevel(targetUnit);
                -- local targetName = UnitName(targetUnit);

                local isBoss = (
                        targetClassification == "worldboss" or
                        targetClassification == "boss" or
                        targetLevel == -1
                );

                if isBoss then
                    DEFAULT_CHAT_FRAME:AddMessage("Entering in combat against a boss")
                end
            end

        elseif unitID == "player" and not UnitInCombat("player") then
            DEFAULT_CHAT_FRAME:AddMessage("leave bossfight")
        end
    end

end);

-- JUST FOR TESTING: fired a chat message if the player turns into combat
frame:SetScript("OnEvent", function(self, event, ...)
    if event == "UNIT_COMBAT" then
        local unitID = select(1, ...)
        if unitID == "player" then
            if UnitInCombat("player") then
                DEFAULT_CHAT_FRAME:AddMessage("DEBUG: entering combat");
            end
        end
    end
end)

